# 파일 경로: pubspec.yaml
name: decathlon_demo_app
description: "A Flutter prototype for Decathlon AI Chatbot with Function Calling and o3 model integration, ready for demonstration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  http: ^1.2.1
  flutter_dotenv: ^5.1.0

  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  speech_to_text: ^6.6.2

  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0

  logging: ^1.2.0 # 로깅 패키지

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/config/